### ISSUE TITLE
BUG - Breaks default nvim behaviour which retains column when moving between lines

### ISSUE THREAD

**Issue by Ajaymamtora** [joshuadanpeterson/typewriter.nvim#16]
When moving between lines with j and k, and:

1) the next line has a shorter length than the current column
2) then the cursor moves to the end of the line.
3) when moving to the next line which has enough columns for the original cursor position (from 1)) -- vim will set it to that column instead of the max length of the previous line.

Step 3 is broken, which means the cursor follows this path:

![image](https://github.com/user-attachments/assets/030e9795-b263-47ec-b81b-c3a10be7a10a)

Instead of:

![image](https://github.com/user-attachments/assets/ba2c7fc1-2faf-4720-94ef-f41edd7f6a67)

Hopefully that makes sense

I've tried changing the config but its broken no matter what i set horizontal scroll and keep cursor position to:

```lua
modules["joshuadanpeterson/typewriter"] = {
  dependencies = {
    'nvim-treesitter/nvim-treesitter',
  },
  version = false,
  config = editor_config.typewriter,
}

....

function config.typewriter()
  local opts = {
    enable_horizontal_scroll = false,
    keep_cursor_position = true,
  }
  require("typewriter").setup(opts)
  vim.cmd(":TWEnable")
end

```

**Comment by joshuadanpeterson** [comment]
@Ajaymamtora Just issued a patch. Try it now and see what you think
