### ISSUE TITLE
[Bug] Conflict with nvim-flash

### ISSUE THREAD

**Issue by Ajaymamtora** [joshuadanpeterson/typewriter.nvim#19]
Sometimes when using fFtT Ss motions -- the cursor is not placed next to the target match. Is there a way this could be fixed please? I tried configuring flash myself but there's no hooks to listen for a search being started or ending so couldn't use an autocmd

I think the autocmd in this plugin adjusts the column, the line is never wrong so it might be to do with the code that remembers a target column

https://github.com/folke/flash.nvim

**Comment by joshuadanpeterson** [comment]
I'll take a look at it. It'll probably take me through the end of next week to get to it because of work and then vacation this weekend.

**Comment by joshuadanpeterson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bug] Conflict with nvim-flash #19](https://trello.com/c/kWQrOCQ5/7-bug-conflict-with-nvim-flash-19)

**Comment by joshuadanpeterson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bug] Conflict with nvim-flash #19](https://trello.com/c/eqCFWdrQ/1-bug-conflict-with-nvim-flash-19)

**Comment by joshuadanpeterson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bug] Conflict with nvim-flash #19](https://trello.com/c/LWxXGpdY/1-bug-conflict-with-nvim-flash-19)

**Comment by joshuadanpeterson** [comment]
@Ajaymamtora Thank you for your help in testing this plugin. I really appreciate it. I submitted a new [PR] #25  to address the recurrence of #16. Hopefully that fixes the issue.
