### ISSUE TITLE
[Bug] TWDisable doesnt disable the autocmd that modifies the column

### ISSUE THREAD

**Issue by Ajaymamtora** [joshuadanpeterson/typewriter.nvim#20]

**Comment by joshuadanpeterson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bug] TWDisable doesnt disable the autocmd that modifies the column #20](https://trello.com/c/xvHOQTsd/2-bug-twdisable-doesnt-disable-the-autocmd-that-modifies-the-column-20)

**Comment by joshuadanpeterson** [comment]
Try this and see if it fixes it.
