### ISSUE TITLE
Searching doesn't move cursor to the correct place

### ISSUE THREAD

**Issue by Rasmus-Bertell** [joshuadanpeterson/typewriter.nvim#21]
I think #17 introduced a bug which makes the cursor stay in it's place even when searching.

Steps to reproduce:

1. Open the config file
2. Search for `M` with `/M`
3. Jump to next result with `n`
4. Cursor is in the wrong place

My config file:
```lua
local M = { 'joshuadanpeterson/typewriter.nvim' }

M.opts = {}

return M
```

```lua
local M = { 'joshuadanpeterson/typewriter.nvim' }
      ^
      First match

M.opts = {}

return M
```

```lua
local M = { 'joshuadanpeterson/typewriter.nvim' }

M.opts = {}
^     ^
|     Cursor position
Second match

return M
```

**Comment by benjaminingreens** [comment]
I am experiencing the same issue. Any know fixes?

**Comment by joshuadanpeterson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Searching doesn't move cursor to the correct place](https://trello.com/c/mrwZLjiK/3-searching-doesnt-move-cursor-to-the-correct-place)

**Comment by joshuadanpeterson** [comment]
@Rasmus-Bertell @benjaminingreens Try it now and let me know if that fixes it.
