### ISSUE TITLE
Docs are missing

### ISSUE THREAD

**Issue by Rasmus-Bertell** [joshuadanpeterson/typewriter.nvim#7]
Tried to run `:help typewriter` but got an error `E429: File "/home/rasmus/.local/share/nvim/lazy/typewriter/doc/typewriter.txt" does not exist`. Looked in the repo and there seems to be only tags-file in the docs folder.

**Comment by joshuadanpeterson** [comment]
I used mini.doc to create the help docs but it didn't render properly. I'll have to fix that this weekend.

**Comment by joshuadanpeterson** [comment]
@Rasmus-Bertell Turns out I had all .txt files listed in my .gitignore so the typewriter.txt file didn't upload to GitHub. I fixed that and regenerated the tags to ensure that `:help typewriter` works properly. Should be fixed now.
