### ISSUE TITLE
TWTop & TWBottom not working

### ISSUE THREAD

**Issue by Rasmus-Bertell** [joshuadanpeterson/typewriter.nvim#8]
Running either `TWTop` or `TWBottom` results in the following error

```bash
Error executing Lua callback: ...l/share/nvim/lazy/typewriter/lua/typewriter/commands.lua:141: attempt to call global 'get_expand_r
oot' (a nil value)
stack traceback:
        ...l/share/nvim/lazy/typewriter/lua/typewriter/commands.lua:141: in function 'move_to_top_of_block'
        ...are/nvim/lazy/typewriter/lua/typewriter/autocommands.lua:49: in function <...are/nvim/lazy/typewriter/lua/typewriter/aut
ocommands.lua:48>
```

The function `get_expand_root` is defined locally inside a previous code block and is therefore unavailable.

https://github.com/joshuadanpeterson/typewriter.nvim/blob/9e15168ab6edd852a6fdfcd6458e6d772723d737/lua/typewriter/commands.lua#L93

**Comment by joshuadanpeterson** [comment]
@Rasmus-Bertell Thanks for calling attention to that. I'll fix that this weekend and let you know.

**Comment by joshuadanpeterson** [comment]
@Rasmus-Bertell Fixed the issue
